### ISSUE TITLE
Error when uploading  new event details

### ISSUE THREAD

**Issue by monicakrylander** [wjdp/abington10k#11]
Get "Error when loading data from GitHub" when trying to amend event details as follows

"The Abington 10k and Fun Run is a yearly running event in aid of Great Abington Primary School".

to read

"The Abington 10k & Fun Run is a yearly running event organised by Great Abington Primary School PTFA (Registered Charity No. 1136090) to raise funds for Great Abington Primary School". 
- then link "Great Abington Primary School" to the school website http://www.greatabingtonprimaryschool.co.uk/ 
- and link "Great Abington Primary School PTFA" to the PTFA webpage http://www.greatabingtonprimaryschool.co.uk/pta

**Comment by wjdp** [comment]
Odd, I'm assuming this is Prose. Try closing the browser down fully, and perhaps clearing cookies for the site.

**Comment by monicakrylander** [comment]
ok, will try this
