### ISSUE TITLE
Get Abington School website to link to this one.

### ISSUE THREAD

**Issue by wjdp** [wjdp/abington10k#12]
A link to this site - http://abington10k.org.uk - from http://www.greatabingtonprimaryschool.co.uk/pta_detail.asp?Section=14&Ref=532 would be very useful.

**Comment by monicakrylander** [comment]
I will look into it

**Comment by monicakrylander** [comment]
have asked to have this done

**Comment by monicakrylander** [comment]
the link is on the school website
