### ISSUE TITLE
Photo link in event.md

### ISSUE THREAD

**Issue by monicakrylander** [wjdp/abington10k#21]
HI Will, 

I tried to add a photo link in the event section, but the link doesn't work. Any ideas?

 [Photos 2015](https://t.co/XYZh0lnbVg/) Courtesy of Jonathan Warren

I have tried this link as well

https://goo.gl/photos/DNqvmDQtwK4n6L2r7

**Comment by monicakrylander** [comment]
Used the link for results, it now works

**Comment by wjdp** [comment]
Nice :smile:
