### ISSUE TITLE
Fix sponsor logos

### ISSUE THREAD

**Issue by wjdp** [wjdp/abington10k#3]
Images, same sizing of logos and links.

**Comment by monicakrylander** [comment]
Total list of sponsors:

PPD
TWI
Biomed
Cheffins
InnotecUK
Abington Stores
Three Tuns
Tees Law
Acorn Garage
Hawthorn 
FAST 
Get Fruity
Up & Running
Swift Timing
Dalehead Foods
Cambridge Water

**Comment by monicakrylander** [comment]
Make PPD logo "stand out" in front of the others as they have donated a large sum of money.

Replace Anagram with Hawthorne, (they have asked us to do this)

**Comment by monicakrylander** [comment]
![ppd-logo-jpeg-pms-268](https://cloud.githubusercontent.com/assets/12464351/8102855/7471ceb6-101b-11e5-8043-90f6b1c87893.jpg)
![ppd-logo-gif-purple](https://cloud.githubusercontent.com/assets/12464351/8102859/7b9798a6-101b-11e5-848d-e437b705b0c6.gif)

**Comment by monicakrylander** [comment]
I kindly ask that you please adhere to the below guidelines in your usage of the logo:

A protection zone equal to the height of the logo (or “P”) must always surround the logo to ensure legibility and visual impact. The zone means that no text or graphic element should be used in this area. The logo may appear over an image or background texture. But only if the image/background is free of enough detail and light enough to not impede legibility or visual impact.

The PPD logo must be used in full without implied connection to any other text, graphic or image. The logo must always include the registered trademark® symbol unless on building signage. You should not use the registered trademark symbol when using the PPD name alone in text. Never modify the logo in any way or attempt to create it from scratch. The only time a device can hold or enclose the PPD logo is with the approved frame structure.

**Comment by monicakrylander** [comment]
![twi logo](https://cloud.githubusercontent.com/assets/12464351/8149007/3fe08130-12ad-11e5-8347-1ce775445cc3.jpg)
![biomed](https://cloud.githubusercontent.com/assets/12464351/8149008/3fe57e10-12ad-11e5-9daf-d5a5c895329a.png)

**Comment by wjdp** [comment]
Cheers

**Comment by wjdp** [comment]
Done
