### ISSUE TITLE
Add License text

### ISSUE THREAD

**Issue by monicakrylander** [wjdp/abington10k#8]
At the top of the page to the right of the Start banner

add "Under UKA rules - License applied for" and Run Britain logo

![runbritain_license logo](https://cloud.githubusercontent.com/assets/12464351/7946869/3b922826-0971-11e5-9766-3595772f2946.jpg)

**Comment by wjdp** [comment]
Will do

**Comment by wjdp** [comment]
That logo has a white background, any chance of one with transparency?

**Comment by monicakrylander** [comment]
I will check

**Comment by wjdp** [comment]
No worries, managed to clean it up
